name: ui_creation_challenges_marc_baneres_farran_gsoc_2025
description: "Ui Creation Challenges Marc Baneres Farran Gsoc 2025"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  dartssh2: ^2.11.0
  path_provider: ^2.1.2
  xml: ^6.4.0
  flutter_animated_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/files/kml/
